In [1]:
import numpy as np
import pandas as pd

In [21]:
#1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr=np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
arr.dtype

dtype('int64')

In [16]:
#2.Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
#arr.dtype
if arr.dtype == np.float64:
    print("true")
else:
    print("false")

true


In [18]:
#3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr=np.array([1 + 2j, 3 + 4j, 5 + 6j],dtype=np.complex128)
arr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [35]:
#4.Convert an existing NumPy array 'arr' of integers to float32 data type.
arr=np.array([1,2,3,4,5])
arr_2 = arr.astype(np.float32)
arr_2

array([1., 2., 3., 4., 5.], dtype=float32)

In [37]:
#5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr=np.array([1.234, 2.345, 3.456],dtype=np.float64)
arr_2=arr.astype(np.float32)
arr_2

array([1.234, 2.345, 3.456], dtype=float32)

In [39]:
#6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print(shape)
print(size)
print(dtype)

(2, 3)
6
int64


In [44]:
#7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    return arr.ndim
arr=np.array([[1, 2, 3], [4, 5, 6]])
dim=array_dimension(arr)
print(dim)

2


In [49]:
#8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in byte.
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = item_size * arr.size
    return item_size,total_size
arr=np.array([[1, 2, 3],[4, 5, 6]])
item_size,total_size=item_size_info(arr)
print(item_size)
print(total_size)

8
48


In [52]:
#9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
     return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print(strides)

(24, 8)


In [53]:
#10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print(shape)
print(strides)

(2, 3)
(24, 8)


In [2]:
#11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with 'n' elements.
def create_zeros_array(n):
    return np.zeros(n)
n=int(input("enter number:"))
zeros_array=create_zeros_array(n)
print(zeros_array)

enter number: 5


[0. 0. 0. 0. 0.]


In [3]:
#12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D Numpy array filled with ones of size 'rows x cols'.
def create_ones_matrix(r,c):
    return np.ones((r,c))
r=int(input("enter row:"))
c=int(input("enter col:"))
ones_mat=create_ones_matrix(r,c)
print(ones_mat)

enter row: 2
enter col: 2


[[1. 1.]
 [1. 1.]]


In [9]:
#13.Write a function `generate_range_array` that takes three integers start,stop,and step as arguments and creates a Numpy array with a range starting from 'start',ending at stop(exclusive),and with the specified 'step'.
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)
start=int(input("enter start:"))
stop=int(input("enter stop:"))
step=int(input("enter step:"))
range_array=generate_range_array(start,stop,step)
print(range_array)

enter start: 1
enter stop: 9
enter step: 2


[1 3 5 7]


In [11]:
#14.Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a numpy array with num equally spaced values between 'start' and 'stop'(inclusive)
def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)
start=int(input("enter start:"))
stop=int(input("enter stop:"))
num=int(input("enter num:"))
linear_space=generate_linear_space(start,stop,num)
print(linear_space)              

enter start: 1
enter stop: 9
enter num: 4


[1.         3.66666667 6.33333333 9.        ]


In [12]:
#15.Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size 'n x n'using 'numpy.eye'.
def create_identity_matrix(n):
    return np.eye(n)
n = int(input("enter the num:"))
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

enter the num: 3


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#16.Write a function that takes a Python list and converts it into a NumPy array.
def list_to_numpy_array(py_list):
    return np.array(py_list)
python_list =input().split(',')
numpy_array = list_to_numpy_array(python_list)
print(numpy_array)

 [1,2,3,4,5]


['[1' '2' '3' '4' '5]']


In [5]:
#17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr=np.array([[1,2,3],[4,5,6]])
arr1=arr.view()
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def conc(arr1,arr2,axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
arr1=np.array([[1, 2], [3, 4]])
arr2=np.array([[5, 6]])
result = conc(arr1, arr2, axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
#19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate'.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [11]:
#20.Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arrays):
    return np.vstack(arrays)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr3 = np.array([[13, 14, 15], [16, 17, 18]])
stacked_array = vertical_stack([arr1, arr2, arr3])
print(stacked_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [19]:
#21.Write a Python function using NumPy to create an array of integers within a specified range(inclusive) with a given step size.
def create_array_with_step(start, stop, step):
    return np.arange(start, stop+1, step, dtype=int)

In [3]:
#22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1(inclusive)
def array2():
    return np.linspace(0, 1, 10)
result = array2()
print(result)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [5]:
#23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000(inclusive)
def array3():
    return np.logspace(0, 3, 5)
result = array3()
print(result)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [7]:
#24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
df

A   B   C
0  83  85   1
1  59  73  42
2   5  47  51
3  64  93  93
4  14  52  91

In [11]:
#25.Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros.Use numpy operations within thw pandas dataframe.
def replace_negative_with_zero(df, column_name):
    df[column_name] = (df[column_name] >= 0) * df[column_name] #np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {'A': [1, -2, 3, -4, 5]}
df = pd.DataFrame(data)
df

A
0  1
1 -2
2  3
3 -4
4  5

In [12]:
df_modified = replace_negative_with_zero(df, 'A')
print(df_modified)

   A
0  1
1  0
2  3
3  0
4  5


In [13]:
#26.Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element) 

30


In [14]:
#27.Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
element= arr_2d[1, 2]
print(element)

6


In [15]:
#28.Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
greater= arr[arr > 5]
print(greater)

[ 8 10  7]


In [16]:
#29.Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sli= arr[2:6]
print(sli)

[3 4 5 6]


In [17]:
#30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [3]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(arr, indices):
    flattened_arr = arr.flatten()
    return flattened_arr[indices]
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
indices = np.array([1,3,7])
result = extract_elements(arr, indices)
print(result)  

[2 4 8]


In [4]:
#32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def greater_than(arr, threshold):
    return arr[arr > threshold]
arr = np.array([1, 5, 10, 15, 20])
threshold = 10
filtered_array = greater_than(arr, threshold)
print(filtered_array)

[15 20]


In [5]:
#33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three seperate arrays for each dimension.
def extract_elements_3d(arr,dim1,dim2,dim3):
    return arr[dim1,dim2,dim3]
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])
dim1 = np.array([0, 1, 2]) 
dim2 = np.array([1, 0, 2]) 
dim3 = np.array([2, 1, 0]) 
extracted_elements = extract_elements_3d(arr_3d,dim1,dim2,dim3)
print(extracted_elements) 

[ 6 11 25]


In [4]:
#34.Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def conditions(arr,indices):
    return arr[(indices[:, 0]) & (indices[:, 1])]
arr = np.array([[1, 2], [3, 4], [5, 6]])
indices = np.array([[True, True], [False, True], [True, False]])
result = conditions(arr, indices)
print(result)

[[1 2]]


In [12]:
#35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided in seperate arrays.
def arr2d(arr, row, col):
    return arr[row, col]
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([0, 1, 2])
result = arr2d(arr, row_indices, col_indices)
print(result)

[1 5 9]


In [13]:
#36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
result = arr + 5
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [15]:
#37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using numpy broadcasting.
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
arr1_transposed = arr1.T
result = arr1_transposed * arr2
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [2]:
#38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using numpy broadcasting.
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],       # Shape (4, 3)
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])
arr1_trans=arr1.T
result = arr1_trans + arr2
print(result)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [4]:
#39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1], [2], [3]])  
arr2 = np.array([[4, 5, 6]])      
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [9]:
#40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting.Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  
arr2 = np.array([[7, 8], [9, 10]])        
arr2_reshaped = arr2.reshape(2, 2, 1)
result = arr1 * arr2_reshaped
print(result)

[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [10]:
#41.Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_means = np.mean(arr, axis=0)
print( column_means)

[2.5 3.5 4.5]


In [11]:
#42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_means = np.mean(arr, axis=1)
print(row_means)

[2. 5.]


In [13]:
#43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)
print(max_indices)

[1 1 1]


In [23]:
#44. For the given array, apply custom function to calculate moving sum along rows.
def moving_sum(row):
    return np.convolve(row, np.ones(3), mode='valid')
arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum_result = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print(arr)
print(moving_sum_result)

[[1 2 3]
 [4 5 6]]
[[ 6.]
 [15.]]


In [14]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
even_columns = np.all(arr % 2 == 0, axis=0)
print(even_columns)

[False False False]


In [2]:
#46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
#original_array = np.array([1, 2, 3, 4, 5, 6])
def reshape_array(original_array, m, n):
    reshaped_matrix = original_array.reshape(m, n)
    return reshaped_matrix
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2  
n = 3  
reshaped_matrix = reshape_array(original_array, m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
#47. Create a function that takes a matrix as input and returns the flattened array.
#input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_array(input_matrix):
    flattened_array=input_matrix.flatten()
    return flattened_array
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_array(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [12]:
#48. Write a function that concatenates two given arrays along a specified axis.
def conc_arr(array1,array2,axis=0):
    concatenated_array = np.concatenate((array1, array2),axis=axis)
    return concatenated_array
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result1 = conc_arr(array1, array2, axis=0)
print(result1)
result2= conc_arr(array1, array2, axis=1)
print(result2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# 49.Create a function that splits an array into multiple sub-arrays along a specified axis.
def split_array(original_array, num_splits, axis=0):
    sub_arrays = np.split(original_array, num_splits, axis=axis)
    return sub_arrays
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = split_array(original_array, 3, axis=0)
print("rows:")
print(result)
result = split_array(original_array, 3, axis=1)
print("\ncolumns:")
print(result)

rows:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

columns:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [ ]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
def insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result_array = insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Result array:")
print(result_array)

In [28]:
#51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.perform element-wise addition between arr1 and arr2.
arr1=np.random.randint(1,10,size=(3,3))
print(arr1)
arr2=np.arange(1,10).reshape((3,3))
print(arr2)
result = arr1 + arr2
print(result)

[[9 9 8]
 [9 1 4]
 [8 7 2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 11]
 [13  6 10]
 [15 15 11]]


In [29]:
#52.Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10.subtract arr2 from arr1 element-wise.
arr1=np.random.randint(1,10,size=(3,3))
print(arr1)
arr2=np.arange(1,10).reshape((3,3))
print(arr2)
result = arr1-arr2
print(result)

[[9 2 5]
 [8 8 6]
 [5 1 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 8  0  2]
 [ 4  3  0]
 [-2 -7 -2]]


In [64]:
#53.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.Perform element-wise multiplication between arr1 and arr2.
arr1 = np.random.randint(1, 11, size=(3, 3)) 
arr2 = np.arange(1, 6) 
arr1_reshaped = arr1.T
result = arr1_reshaped * arr2
print(result)

ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

In [53]:
#54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5.Perform element -wise division of arr1 by arr2
arr1 = np.arange(2, 11, 2)  
arr2 = np.arange(1, 6)  
result= arr1 / arr2  
print(result)

[2. 2. 2. 2. 2.]


In [54]:
#55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed.Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.
arr1 = np.arange(1, 6)  
arr2 = np.flip(arr1) 
result= np.power(arr1, arr2)  
print(result)

[ 1 16 27 16  5]


In [45]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_substring_occurrences(arr, substring):
    count = 0
    for string in arr:
        count += string.count(substring)
    return count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print(occurrences)

3


In [44]:
#57.Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = [char for string in arr for char in string if char.isupper()]
print(uppercase_chars)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [61]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
def replace(arr,old_arr,new_arr):
    return np.array([string.replace(old_arr,new_arr)for string in arr])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace(arr, 'banana', 'orange')
print(new_arr)

['apple' 'orange' 'grape' 'pineapple']


In [62]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
def conc(arr1,arr2):
    return np.array([arr1[i] + arr2[i] for i in range(len(arr1))])
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = conc(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


In [63]:
#60. Write a function that finds the length of the longest string in a NumPy array.
def longest(arr):
    lengths = np.array([len(string) for string in arr])
    return np.max(lengths)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest(arr)
print(longest_length)

9


In [2]:
#61.Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using numpy's functions.
dataset = np.random.randint(1, 1001, 100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print(dataset)
print(mean)
print(median)
print(variance)
print(std_deviation)

[654 384 380 314 762 811 680  53  67 714 520 325 768 661 843 467 175 142
 863 257 454 892 253 505 799  25 352 649 895  64 685 295 837 744 913 846
 555 338  25 395 685 705 420  85 974 133 880 890 423 862 268 221 798 887
 340 540 623 215 175 556  50 596   1 422 170   7 818 529  87 428 783 440
 903 386 668 475 305 754   4 908 548 426   8 392 393 604 924  95 361 319
 936 518 763 882 913 791 922 805 282 278]
509.35
511.5
83660.58750000001
289.2414000450143


In [3]:
#62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
d= np.random.randint(1, 101, 50)
per1 = np.percentile(dataset, 25)
per2= np.percentile(dataset, 75)
print(d)
print(per1)
print(per2)

[ 8 51  9 12 30 55 43 53 24 92  5 69 51 97 44 58 45 71 40 68 14 27 49 75
 81 72 97 18 81 39 12 97 41 81 87 82 85 72 46 52 11 10 53 37 66 78 83 62
  3 78]
291.75
785.0


In [4]:
#63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using numpy's corrcoef function
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])
corr= np.corrcoef(array1, array2)[0, 1]
print(corr)

-0.9999999999999999


In [5]:
#64.Create two matrices and perform matrix multiplication using NumPy's `dot` function.
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])
result = np.dot(matrix1, matrix2)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [9]:
#65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr=np.random.randint(10,1001,50)
percentiles = np.percentile(arr, [10, 25, 50, 75, 90])
print("Array:",arr)
print("10th Percentile:", percentiles[0])
print("25th Percentile (First Quartile):", percentiles[1])
print("50th Percentile (Median):", percentiles[2])
print("75th Percentile (Third Quartile):", percentiles[3])
print("90th Percentile:", percentiles[4])

Array: [815 330 904 187 453  45 871 486 758 116 153 769 613 839 475 692 648 176
 218 910 991 350 522 265 589 398 932  80 193 371 320 174 892 372 261 682
 978 263  11 285 566 845 302 483 701 176 188 882 544 905]
10th Percentile: 171.9
25th Percentile (First Quartile): 261.5
50th Percentile (Median): 479.0
75th Percentile (Third Quartile): 766.25
90th Percentile: 904.1


In [10]:
#66. Create a NumPy array of integers and find the index of a specific element.
arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])
element= 9
indices = np.argwhere(arr == element).flatten()
print(arr)
print(element,indices)

[ 1  3  5  7  9 11 13 15]
9 [4]


In [11]:
#67. Generate a random NumPy array and sort it in ascending order.
random_array = np.random.randint(1, 100, size=10)
sorted_array = np.sort(random_array)
print(random_array)
print(sorted_array)

[48 73 98 41 11 54 37  7 38 66]
[ 7 11 37 38 41 48 54 66 73 98]


In [12]:
#68.Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
filterr= arr[arr > 20]
print(filterr)

[25 42 30]


In [14]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
filterr=arr[arr%3==0]
print(filterr)

[12 15]


In [16]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
filterr=arr[(arr >= 20) & (arr <= 40)]
print(filterr)

[20 30 40]


In [18]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)

=


In [19]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)

[16777216 33554432 50331648]


In [20]:
#73.For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)
swapped= arr.newbyteorder()
print(swapped)

[16777216 33554432 50331648]


In [21]:
#74.For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder('<' if arr.dtype.byteorder != '=' else '=')
print(swapped_arr)

[1 2 3]


In [22]:
#75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute byteorder
arr = np.array([1, 2, 3], dtype=np.int32)
byte_swapping_needed = arr.dtype.byteorder != '='
print(byte_swapping_needed )

False


In [32]:
#76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element  in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print(arr1)
print(copy_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]


In [33]:
#77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix . Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 999
print(matrix)
print(view_slice)

[[999  81  23]
 [ 65  58  53]
 [ 43  66  35]]
[[999  81]
 [ 65  58]]


In [34]:
#78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print(array_a)
print(view_b)

[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
[[ 6  7]
 [ 9 10]]


In [31]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 'reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`. 
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 100
print(orig_array)
print(reshaped_view)

[[100   2   3   4]
 [  5   6   7   8]]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [30]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
data = np.random.randint(1, 10, size=(3, 4))
data_copy = np.copy(data[data > 5])
data_copy[0] = 10
print(data)
print(data_copy)

[[7 2 1 7]
 [6 1 9 6]
 [9 5 5 8]]
[10  7  6  9  6  9  8]


In [24]:
#81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])
add= A + B
sub= A - B
print(add)
print(sub)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [25]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])
D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])
mul=np.dot(C, D)
print(mul)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [26]:
#83. Create a matrix `E` and find its transpose.
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
e=E.T
print(e)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
#84. Generate a square matrix `F` and compute its determinant.
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
f= np.linalg.det(F)
print(f)

0.0


In [28]:
#85. Create a square matrix `G` and find its inverse.
G = np.array([[1, 2],
              [3, 4]])
inverse=np.linalg.inv(G)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]
